# Generated by Django 2.0.5 on 2018-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_data',
            fields=[
                ('session_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('usr_data', models.TextField()),
                ('total_img', models.IntegerField()),
                ('spp', models.IntegerField()),
            ],
        ),
    ]
