# Generated by Django 2.0.5 on 2018-05-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_data',
            name='lock',
        ),
    ]
